### ISSUE TITLE
Things to do to make the code can be used on Nao V6?

### ISSUE THREAD

**Issue by SkyCloudShang** [bhuman/BHumanCodeRelease#33]
Hello,
      I want to know what I need to do so that the code can be used on Nao V6. I tried to use alcommon and boost in SDK version 2.8.3.54-linux64 to compile them into bhuman code. I found some bottom-level errors about libs such as Eigen. These errors seem to be based on 32-bit architecture. Currently, V6 2.8 system only provides 64-bit sdk, so the architecture does not match well. I wonder if my understanding is correct?  If so, what can I do to eventually use Bhuman code on my V6 robot? Because at present I only have V6 robots around me, and I am very interested in the software system of bhuman. You have done a great job. Many partners in China are learning your system. I also want to use it on my robot as soon as possible, so I hope to know what I should do next. Thank you!

The build errors seems like this as following:

In file included from ../../Src/Modules/Perception/FieldPerceptors/PenaltyMarkPerceptor.cpp:9:
In file included from ../../Src/Modules/Perception/FieldPerceptors/PenaltyMarkPerceptor.h:11:
In file included from ../../Src/Representations/Configuration/FieldDimensions.h:12:
In file included from ../../Src/Tools/Boundary.h:11:
In file included from ../../Src/Tools/Math/Eigen.h:18:
In file included from ../../Util/SimRobot/Util/Eigen/Eigen/StdVector:14:
In file included from ../../Util/SimRobot/Util/Eigen/Eigen/Core:176:
In file included from ../../Util/Buildchain/clang/include/emmintrin.h:31:
../../Util/Buildchain/clang/include/xmmintrin.h:1373:10: error: use of undeclared identifier '__builtin_ia32_cvttss2si'; did you mean '__builtin_ia32_cvtss2si'?
  return __builtin_ia32_cvttss2si((__v4sf)__a);
         ^~~~~~~~~~~~~~~~~~~~~~~~
         __builtin_ia32_cvtss2si
../../Util/Buildchain/clang/include/xmmintrin.h:1282:10: note: '__builtin_ia32_cvtss2si' declared here
  return __builtin_ia32_cvtss2si((__v4sf)__a);
         ^
../../Util/Buildchain/clang/include/xmmintrin.h:2965:44: error: token is not a valid binary operator in a preprocessor subexpression
#if defined(__SSE2__) && !__building_module(_Builtin_intrinsics)

**Comment by bhuman** [comment]
There will be an announcement by SoftBank in the middle of December on how to program the NAO V6.

To compile for the NAO V6, you have to replace everything in Util/Buildchain/gcc Util/Buildchain/clang with the files from the V6 cross toolchain. Then you have to update the include paths and library names in the mare files for the robot. It might be the case that the intrinsics your desktop clang understands are not the same as the ones that come with the cross toolchain. You have to adapt them if that is the case. The software on the NAO V6 is still 32 bit. Only the kernel is 64 bit.

If you can compile the software, it still won't work on the NAO, because NAOqi 2.8 lacks the DeviceCommunicationManager.

There probably also will be an announcement about how to work with the cameras, which are USB devices now.

**Comment by SkyCloudShang** [comment]
All right. Thank you for your reply. I wonder if your code release will be open to GitHub after it adapts to V6. We hope that we can use bhuman on Nao V6 earlier. Maybe for us, the adaptation process is still very difficult. So when you adapt code release to V6, can you open up a part of it? Thank you!

**Comment by bhuman** [comment]
Our next code release will probably be in autumn 2019. All teams have to figure out how to control the NAO V6. That includes the teams that base their system on our code.

**Comment by SkyCloudShang** [comment]
> There will be an announcement by SoftBank in the middle of December on how to program the NAO V6.
> 
> To compile for the NAO V6, you have to replace everything in Util/Buildchain/gcc Util/Buildchain/clang with the files from the V6 cross toolchain. Then you have to update the include paths and library names in the mare files for the robot. It might be the case that the intrinsics your desktop clang understands are not the same as the ones that come with the cross toolchain. You have to adapt them if that is the case. The software on the NAO V6 is still 32 bit. Only the kernel is 64 bit.
> 
> If you can compile the software, it still won't work on the NAO, because NAOqi 2.8 lacks the DeviceCommunicationManager.
> 
> There probably also will be an announcement about how to work with the cameras, which are USB devices now.


Hello, I want to know if Softbank officially has a document published on Nao V6? I have not seen any new LoLA related documents on the official website. Do you have that over there? I only saw a brief introduction to LoLA in the link http://doc.aldebaran.com/2-8/naoqi/lola/lola.html, there is no corresponding api or the like. There are no descriptions of interfaces such as onPreProcess and onPostProcess of the previous dcm module.

**Comment by bhuman** [comment]
You may want to ask your question here: https://spl.robocup.org/committees-2019/
